jobs:
- template: 'azure-template.yml'
  parameters:
    name: 'macOS_stable'
    vmImage: 'xcode9-macos10.13'
    toolchain: 'stable'

- template: 'azure-template.yml'
  parameters:
    name: 'macOS_beta'
    vmImage: 'macOS-10.13'
    toolchain: 'beta'

- template: 'azure-template.yml'
  parameters:
    name: 'macOS_nightly'
    vmImage: 'macos10.13'
    toolchain: 'nightly'

- template: 'azure-template.yml'
  parameters:
    name: 'macOS_1_25_0'
    vmImage: 'macos10.13'
    toolchain: '1.25.0'

- template: 'azure-template.yml'
  parameters:
    name: 'Linux_stable'
    vmImage: 'ubuntu-16.04'
    toolchain: 'stable'

- template: 'azure-template.yml'
  parameters:
    name: 'Linux_beta'
    vmImage: 'ubuntu-16.04'
    toolchain: 'beta'

- template: 'azure-template.yml'
  parameters:
    name: 'Linux_nightly'
    vmImage: 'ubuntu-16.04'
    toolchain: 'nightly'

- template: 'azure-template.yml'
  parameters:
    name: 'Linux_1_25_0'
    vmImage: 'ubuntu-16.04'
    toolchain: '1.25.0'
