[package]
name = "e09_collectors"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies.serenity]
features = ["collector", "framework", "rustls_backend"]
path = "../../"

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
