[package]
name = "e15_voice_storage"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[dependencies.serenity]
features = ["cache", "framework", "standard_framework", "voice", "http", "rustls_backend"]
path = "../../"

[dependencies.songbird]
path = "../../songbird"

[dependencies.tokio]
version = "0.2"
features = ["macros"]
