[package]
name = "09_shard_manager"
version = "0.1.0"
authors = ["my name <my@email.address>"]

[dependencies]
env_logger = "~0.4"
log = "~0.4"

[dependencies.serenity]
features = ["client"]
path = "../../"
