[package]
name = "e12_global_data"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
serenity = { path = "../../" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
dashmap = "5"
